SELECT * FROM BOOKING B INNER JOIN USER U ON B.user_id = U.id;

SELECT * FROM PROPERTY P LEFT JOIN REVIEWS R ON P.property_id = R.property_id;

SELECT * FROM USER U FULL OUTER JOIN BOOKING B ON U.id=B.user_id;